name: Release
on:
  release:
    types: [published]

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Update Version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          npm version $VERSION --no-git-tag-version
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: bump version to ${{ github.ref_name }}"
          title: "chore: bump version to ${{ github.ref_name }}"
          body: "Automated version bump triggered by release ${{ github.ref_name }}"
          branch: "version-bump/${{ github.ref_name }}"
          base: "main"
